fix inception

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,9 +47,11 @@ jobs:
           VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
         run: |
+          set -e  # Exit immediately if a command exits with a non-zero status
+      
           export ENV_LOCAL=$(echo ${{ inputs.VAULT_KV_PATH }} | cut -d "/" -f 3)
       
-          # Try to fetch secrets from Vault and handle potential errors
+          # Fetch secrets from Vault and handle potential errors
           if ! vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }} | sed 's/: /=/' > env-mf; then
             echo "Error: Unable to fetch secrets from ${{ inputs.VAULT_KV_PATH }}"
             exit 1
@@ -61,7 +63,7 @@ jobs:
           fi
       
           sort -u -t '=' -k 1,1 env-cloud env-mf > .env
-          
+
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v0
         with:
