handle error when retrieving secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,16 +41,27 @@ jobs:
         with:
           vpn_config: ${{ secrets.VPN_CONFIG }}
           vpn_pass: ${{ secrets.VPN_PASS }}
+
       - name: Vault Secrets to env
         env:
           VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
         run: |
           export ENV_LOCAL=$(echo ${{ inputs.VAULT_KV_PATH }} | cut -d "/" -f 3)
-
-          vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }}| sed 's/: /=/' > env-mf
-          vault kv get -format yaml -field=data cloud-infra-mf/$ENV_LOCAL| sed 's/: /=/' > env-cloud
+      
+          # Try to fetch secrets from Vault and handle potential errors
+          if ! vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }} | sed 's/: /=/' > env-mf; then
+            echo "Error: Unable to fetch secrets from ${{ inputs.VAULT_KV_PATH }}"
+            exit 1
+          fi
+      
+          if ! vault kv get -format yaml -field=data cloud-infra-mf/$ENV_LOCAL | sed 's/: /=/' > env-cloud; then
+            echo "Error: Unable to fetch secrets from cloud-infra-mf/$ENV_LOCAL"
+            exit 1
+          fi
+      
           sort -u -t '=' -k 1,1 env-cloud env-mf > .env
+          
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v0
         with:
