fix trap

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,21 +46,20 @@ jobs:
         env:
           VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
+        shell: bash
         run: |
-          export ENV_LOCAL=$(echo ${{ inputs.VAULT_KV_PATH }} | cut -d "/" -f 3)
-      
-          # Fetch secrets from Vault and handle potential errors
-          vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }} | sed 's/: /=/' > env-mf || {
-            echo "Error: Unable to fetch secrets from ${{ inputs.VAULT_KV_PATH }}"
-            exit 1
-          }
-      
-          vault kv get -format yaml -field=data cloud-infra-mf/$ENV_LOCAL | sed 's/: /=/' > env-cloud || {
-            echo "Error: Unable to fetch secrets from cloud-infra-mf/$ENV_LOCAL"
-            exit 1
-          }
-      
-          sort -u -t '=' -k 1,1 env-cloud env-mf > .env
+          set -e  # Exit immediately if a command exits with a non-zero status
+
+          vault_kv_path="${{ inputs.VAULT_KV_PATH }}"
+          env_local=$(echo "$vault_kv_path" | cut -d '/' -f 3)
+          cloud_infra_path="cloud-infra-mf/$env_local"
+
+          # Trap errors to provide more informative messages
+          trap 'echo "Error fetching secrets from $cloud_infra_path: $@" >&2' ERR
+
+          # Fetch secrets and handle potential errors
+          vault kv get -format yaml -field=data "$vault_kv_path" | sed 's/: /=/' > env-local
+          vault kv get -format yaml -field=data "$cloud_infra_path" | sed 's/: /=/' > env-cloud
 
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v0
